import { Heading } from "@components/Heading";
import { Link } from "@components/Link";
import { ListItem, UnorderedList } from "@components/List";
import { PageLayout } from "@components/PageLayout";
import { Paragraph } from "@components/Paragraph";

export default function AiPage() {
  return (
    <PageLayout title="AI Policy">
      <Paragraph>
        The availabilty of Large Language Models for general use has had an
        undeniable impact on the state of software development over the past few
        years. Specialized and &ldquo;everything&rdquo; models alike can
        generate massive amounts of code for almost any program imaginable.
        Generating a website like my own or its projects would not be a complex
        feat using the latest AI models and specific enough prompts.
      </Paragraph>

      <Heading level={2}>Professional AI Use</Heading>

      <Paragraph>
        I believe it is important for today&apos;s engineers to have a thorough
        understanding of the strengths and limitations of these tools.
        Maintaining code that can be understood and manipulated by both humans
        and AI is now a core responsibility of engineers at enterprise
        organizations. As such, I create and use these tools daily on the job,
        including...
      </Paragraph>

      <UnorderedList>
        <ListItem>Custom agents and subagents</ListItem>
        <ListItem>Agent skills</ListItem>
        <ListItem>MCP servers</ListItem>
        <ListItem>
          AI Frameworks (e.g.{" "}
          <Link
            external
            href="https://github.com/teambrilliant/claude-research-plan-implement"
          >
            Research &mdash; Plan &mdash; Implement
          </Link>
          )
        </ListItem>
        <ListItem>Project-specific context for LLMs</ListItem>
        <ListItem>AI-driven PR reviews</ListItem>
      </UnorderedList>

      <Heading level={2}>Personal AI Use</Heading>

      <Paragraph>
        My site and its projects have different goals than the software at
        enterprise organizations. I use the act of building them to expand my
        understanding of coding techniques and technologies that I want to
        explore. The projects are ones I get excited about programming directly
        instead of handing them off to a web of agents. As such, I am very
        selective of how I use AI outside of work.
      </Paragraph>

      <Paragraph>
        As of now, I&apos;ve only used the following AI tools while developing
        the projects shared on this site:
      </Paragraph>

      <UnorderedList>
        <ListItem>
          Code completion suggestions in IDE via GitHub Copilot
        </ListItem>
        <ListItem>Chats with AI chatbots such as ChatGPT/Claude</ListItem>
      </UnorderedList>

      <Paragraph>
        I did not use agents to generate code for these projects. Any chats that
        generated code snippets were used selectively with a complete
        understanding of the solution offered. I never copied a complete
        file/group of files generated by a chat for my own use in these
        projects.
      </Paragraph>

      <Paragraph>
        That being said, I used AI agents to build parts of shanemcfadden.dev. I
        anticipate that I will begin using agentic engineering techniques for
        some future personal projects to better understand how far I can push
        this technology in a meaningful direction.
      </Paragraph>

      <Paragraph>
        Should I begin using agents to develop the projects on this site, I will
        add indicators to each project page outlining how I used AI to
        build/maintain each project. For now, safely assume that all project
        source code was written directly by me.
      </Paragraph>
    </PageLayout>
  );
}
